.TH JSATTACH 1
.SH NAME
jsattach \- attach a serial line to a joystick device
.SH SYNOPSIS
.B jsattach
<mode> <device>
.SH DESCRIPTION
.B jsattach
is used for attaching a serial line to a joystick device via a 
line dicipline.
.PP
Exactly one of the following modes must be specified on the command
line.
.SH MODES
.TP
.I \--sball4
Use this option for the SpaceBall 4000 FLX.
.TP
.I \--spaceorb
Use this option for the SpaceOrb 360 or SpaceBall Avenger.
.TP
.I \--magellan
Use this option for the Magellan or SpaceMouse.
.TP
.I \--warrior
Use this option for the WingMan Warrior.
.SH SEE ALSO
\fBjscal\fP(1), \fBjstest\fP(1).
